// LEXIAA V19 - avatar render wrappers preserved from verified V18 build.

let sb=null,session=null,user=null;
const $=x=>document.getElementById(x);
function msg(x){$('toast').textContent=x;$('toast').classList.add('show');clearTimeout(window.tm);window.tm=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function page(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='home')loadHomeChampion();document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('on',(b?x===b:x.dataset.page===id)));if(id==='photos')loadPhotos();if(id==='music')loadMusic();if(id==='games'){loadScores();loadLeaderboard();loadWallet();}if(id==='profile')profile();scrollTo(0,0)}
function openM(t,b){$('mt').textContent=t;$('mb').innerHTML=b;$('modal').classList.add('show')}function closeM(){$('modal').classList.remove('show')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function authFeature(target){if(!user)return openAuth();page(target==='Games'?'games':'ai')}
function openAuth(){openM('Login / Daftar',`<form class="form" onsubmit="login(event)"><label>Email<input name="e" type="email" required></label><label>Password<input name="p" type="password" required minlength="6"></label><button class="btn primary">Login</button><button type="button" class="btn" onclick="signupForm()">Daftar akun baru</button></form>`)}
function signupForm(){openM('Daftar',`<form class="form" onsubmit="signup(event)"><label>Nama<input name="n" required></label><label>Email<input name="e" type="email" required></label><label>Password<input name="p" type="password" required minlength="6"></label><button class="btn primary">Daftar</button></form>`)}
async function login(e){e.preventDefault();let f=new FormData(e.target),r=await sb.auth.signInWithPassword({email:f.get('e'),password:f.get('p')});if(r.error)return msg(r.error.message);closeM();msg('Login berhasil')}
async function signup(e){e.preventDefault();let f=new FormData(e.target),email=f.get('e');let r=await sb.auth.signUp({email,password:f.get('p'),options:{data:{display_name:f.get('n')}}});if(r.error){let m=r.error.message||'';if(/rate limit|email rate limit|too many/i.test(m))return msg('Pendaftaran email sedang dibatasi Supabase. Tunggu beberapa menit atau gunakan email lain.');return msg(m)}closeM();msg(r.data.session?'Akun dibuat.':'Cek email untuk konfirmasi.')}
async function init(){let c=window.LEXIAA_CONFIG||{};if(!c.SUPABASE_URL||!c.SUPABASE_PUBLISHABLE_KEY){profile();return}sb=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY);let r=await sb.auth.getSession();apply(r.data.session);sb.auth.onAuthStateChange((_e,s)=>apply(s))}
async function apply(s){session=s;user=s?.user||null;profile();avatar();loadHomeChampion();if(document.querySelector('#photos.active'))loadPhotos();if(document.querySelector('#music.active'))loadMusic();if(document.querySelector('#games.active')){loadScores();loadLeaderboard();loadWallet()}}
async function ensure(){if(!user)return;let r=await sb.from('profiles').select('id').eq('id',user.id).maybeSingle();if(!r.data)await sb.from('profiles').insert({id:user.id,display_name:user.user_metadata?.display_name||user.email.split('@')[0]})}
async function avatar(){if(!user){$('ava').className='ava';$('ava').textContent='L';return}await ensure();let r=await sb.from('profiles').select('avatar_path,display_name').eq('id',user.id).maybeSingle();let el=$('ava');el.className='ava';el.textContent=(r.data?.display_name||'L')[0].toUpperCase();if(r.error||!r.data?.avatar_path)return;let u=await sb.storage.from('avatars').createSignedUrl(r.data.avatar_path,3600);if(u.error||!u.data?.signedUrl)return;el.innerHTML='<img alt="Profile" src="'+u.data.signedUrl+(u.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'">'}
function addPhoto(){if(!user)return openAuth();$('pi').value='';$('pi').click()}$('pi').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;msg('Uploading…');let path=user.id+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');let u=await sb.storage.from('photos').upload(path,f,{contentType:f.type,upsert:false});if(u.error)return msg(u.error.message);let d=await sb.from('photos').insert({user_id:user.id,storage_path:path,file_name:f.name});if(d.error){await sb.storage.from('photos').remove([path]);return msg(d.error.message)}msg('Foto ditambahkan');loadPhotos()}
async function loadPhotos(){if(!user){$('photoList').innerHTML='<div class="empty">Login untuk melihat album.</div>';return}let r=await sb.from('photos').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(r.error){$('photoList').innerHTML='<div class="empty">Gagal memuat foto.<br><small>'+esc(r.error.message)+'</small></div>';return}if(!r.data.length){$('photoList').innerHTML='<div class="empty">Belum ada foto.</div>';return}let out='';for(let x of r.data){let u=await sb.storage.from('photos').createSignedUrl(x.storage_path,3600);let signed=u.data?.signedUrl||'';let safePath=encodeURIComponent(x.storage_path);let safeName=encodeURIComponent(x.file_name);out+=`<div class="item photo-item" onclick="openPhotoByPath('${safePath}','${safeName}')" style="cursor:zoom-in"><div class="thumb">${signed?'<img src="'+signed+(signed.includes('?')?'&':'?')+'v='+Date.now()+'" alt="'+esc(x.file_name)+'">':'◌'}</div><div class="main"><b>${esc(x.file_name)}</b><small>${new Date(x.created_at).toLocaleString('id-ID')} · Ketuk untuk buka & zoom</small></div><button class="btn" onclick="event.stopPropagation();openPhotoByPath('${safePath}','${safeName}')">⌕</button><button class="btn" onclick="event.stopPropagation();dl('${safePath}')">↓</button><button class="btn danger" onclick="event.stopPropagation();delPhoto('${x.id}','${safePath}')">×</button></div>`}$('photoList').innerHTML=out} 
async function openPhotoByPath(path,name){if(!user)return openAuth();let p=decodeURIComponent(path),n=decodeURIComponent(name||'Photo');let u=await sb.storage.from('photos').createSignedUrl(p,3600);if(u.error||!u.data?.signedUrl)return msg('Foto tidak dapat dibuka: '+(u.error?.message||'signed URL gagal'));openPhoto(encodeURIComponent(u.data.signedUrl),encodeURIComponent(n))}
let photoZoom=1,photoX=0,photoY=0,photoStartDist=0,photoStartZoom=1,photoDrag=false,photoLastX=0,photoLastY=0;
function openPhoto(encodedUrl,name){if(!encodedUrl)return msg('Preview foto tidak tersedia');let img=$('photoViewerImg');img.src=decodeURIComponent(encodedUrl);$('photoTitle').textContent=decodeURIComponent(name||'Photo');photoZoom=1;photoX=0;photoY=0;applyPhotoTransform();$('photoModal').classList.add('show')}
function closePhoto(){$('photoModal').classList.remove('show');$('photoViewerImg').src=''}
function applyPhotoTransform(){let img=$('photoViewerImg');img.style.transform=`translate3d(${photoX}px,${photoY}px,0) scale(${photoZoom})`}
function zoomPhoto(delta){photoZoom=Math.min(5,Math.max(1,photoZoom+delta));if(photoZoom===1){photoX=0;photoY=0}applyPhotoTransform()}
function resetPhotoZoom(){photoZoom=1;photoX=0;photoY=0;applyPhotoTransform()}
$('photoViewerImg').addEventListener('dblclick',()=>zoomPhoto(photoZoom>1?-1:1));
$('photoStage').addEventListener('wheel',e=>{e.preventDefault();zoomPhoto(e.deltaY<0?0.2:-0.2)},{passive:false});
$('photoStage').addEventListener('touchstart',e=>{if(e.touches.length===2){photoStartDist=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);photoStartZoom=photoZoom}else if(e.touches.length===1&&photoZoom>1){photoDrag=true;photoLastX=e.touches[0].clientX;photoLastY=e.touches[0].clientY}}, {passive:true});
$('photoStage').addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();let d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);photoZoom=Math.min(5,Math.max(1,photoStartZoom*(d/photoStartDist)));applyPhotoTransform()}else if(e.touches.length===1&&photoDrag&&photoZoom>1){e.preventDefault();let dx=e.touches[0].clientX-photoLastX,dy=e.touches[0].clientY-photoLastY;photoLastX=e.touches[0].clientX;photoLastY=e.touches[0].clientY;photoX+=dx;photoY+=dy;applyPhotoTransform()}},{passive:false});
$('photoStage').addEventListener('touchend',e=>{if(e.touches.length===0)photoDrag=false});
async function dl(p){let r=await sb.storage.from('photos').download(decodeURIComponent(p));if(r.error)return msg(r.error.message);let u=URL.createObjectURL(r.data),a=document.createElement('a');a.href=u;a.download=decodeURIComponent(p).split('/').pop();a.click();URL.revokeObjectURL(u)}
async function delPhoto(id,p){if(!confirm('Hapus foto?'))return;let r=await sb.from('photos').delete().eq('id',id).eq('user_id',user.id);if(r.error)return msg(r.error.message);await sb.storage.from('photos').remove([decodeURIComponent(p)]);loadPhotos()}
function addMusic(){if(!user)return openAuth();$('mi').value='';$('mi').click()}$('mi').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;msg('Uploading…');let path=user.id+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');let u=await sb.storage.from('music').upload(path,f,{contentType:f.type,upsert:false});if(u.error)return msg(u.error.message);let d=await sb.from('music').insert({user_id:user.id,storage_path:path,title:f.name});if(d.error){await sb.storage.from('music').remove([path]);return msg(d.error.message)}msg('Musik ditambahkan');loadMusic()}
async function loadMusic(){if(!user){$('musicList').innerHTML='<div class="empty">Login untuk melihat musik.</div>';return}let r=await sb.from('music').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(r.error)return $('musicList').innerHTML='<div class="empty">'+esc(r.error.message)+'</div>';if(!r.data.length)return $('musicList').innerHTML='<div class="empty">Belum ada musik.</div>';let out='';for(let x of r.data){let u=await sb.storage.from('music').createSignedUrl(x.storage_path,900);out+=`<div class="item"><div class="thumb">♪</div><div class="main"><b>${esc(x.title)}</b>${u.data?.signedUrl?'<audio controls preload="none" style="width:100%;margin-top:6px" src="'+u.data.signedUrl+'"></audio>':''}</div><button class="btn" onclick="dlMusic('${encodeURIComponent(x.storage_path)}','${encodeURIComponent(x.title)}')">↓</button><button class="btn danger" onclick="delMusic('${x.id}','${encodeURIComponent(x.storage_path)}')">×</button></div>`}$('musicList').innerHTML=out}
async function dlMusic(p,name){let r=await sb.storage.from('music').download(decodeURIComponent(p));if(r.error)return msg(r.error.message);let u=URL.createObjectURL(r.data),a=document.createElement('a');a.href=u;a.download=decodeURIComponent(name||p).split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function delMusic(id,p){if(!confirm('Hapus musik?'))return;let r=await sb.from('music').delete().eq('id',id).eq('user_id',user.id);if(r.error)return msg(r.error.message);let st=await sb.storage.from('music').remove([decodeURIComponent(p)]);if(st.error)return msg('Database terhapus, tetapi file gagal dihapus: '+st.error.message);msg('Musik dihapus');loadMusic()}
function ai(tool){if(!user)return openAuth();openM('AI '+tool,'<div class="empty">AI tool siap. Provider AI dapat disambungkan melalui backend tanpa menaruh secret key di frontend.</div>')}
let tapScore=0,tapStart=0,tapTimer=null;const quiz=[['Apa fungsi utama RLS di Supabase?',['Mengatur akses data berdasarkan policy','Mengompres gambar','Mengubah password'],0],['Format audio yang umum di web adalah…',['MP3','PSD','SVG'],0],['Secret/service_role key seharusnya disimpan di…',['Backend/Edge Function','HTML frontend','CSS'],0]];
function game(name){if(!user)return openAuth();if(name==='Quick Tap')startTap();else startQuiz()}
function startTap(){openM('Quick Tap',`<div class="empty">Tap sebanyak mungkin dalam 10 detik.</div><button class="btn primary" style="margin-top:10px;width:100%;height:90px;font-size:28px" onclick="beginTap()">Mulai</button>`)}
function beginTap(){tapScore=0;tapStart=Date.now();openM('Quick Tap',`<div class="empty"><b id="tapTime">10.0</b> detik · Score <b id="tapScore">0</b></div><button class="btn primary" style="margin-top:10px;width:100%;height:120px;font-size:30px" onclick="tap()">TAP!</button>`);clearInterval(tapTimer);tapTimer=setInterval(()=>{let left=10-(Date.now()-tapStart)/1000;let t=$('tapTime');if(t)t.textContent=Math.max(0,left).toFixed(1);if(left<=0){clearInterval(tapTimer);finishTap()}},100)}
function tap(){if(Date.now()-tapStart>=10000)return;tapScore++;let e=$('tapScore');if(e)e.textContent=tapScore}
function finishTap(){openM('Quick Tap — Selesai',`<div class="empty">Score: <b>${tapScore}</b></div><button class="btn primary" style="margin-top:10px" onclick="saveScore('Quick Tap',${tapScore})">Simpan score</button>`)}
let qi=0,qc=0;
function startQuiz(){qi=0;qc=0;showQ()}
function showQ(){if(qi>=quiz.length)return finishQuiz();let q=quiz[qi];openM('Quiz',`<div style="color:var(--m);font-size:12px">Pertanyaan ${qi+1}/${quiz.length}</div><h3>${esc(q[0])}</h3><div class="form">${q[1].map((a,i)=>`<button class="btn" onclick="answerQ(${i})">${esc(a)}</button>`).join('')}</div>`)}
function answerQ(i){if(i===quiz[qi][2])qc++;qi++;showQ()}
function finishQuiz(){let score=qc*100;openM('Quiz — Selesai',`<div class="empty">Benar: <b>${qc}/${quiz.length}</b><br>Score: <b>${score}</b></div><button class="btn primary" style="margin-top:10px" onclick="saveScore('Quiz',${score})">Simpan score</button>`)}
async function saveScore(game,score){if(!user)return openAuth();let r=await sb.rpc('save_game_score',{p_game:game,p_score:Math.max(0,Math.floor(score))});if(r.error)return msg('Gagal menyimpan score: '+r.error.message);let result=Array.isArray(r.data)?r.data[0]:r.data;closeM();await loadScores();await loadLeaderboard();await loadWallet();let earned=Number(result?.diamonds_earned||0);await loadHomeChampion();msg(earned>0?`Score tersimpan · +${earned} 💎`:'Score tersimpan')}
async function loadWallet(){if(!$('diamondBalance'))return;if(!user){$('diamondBalance').textContent='0';return}let r=await sb.from('profiles').select('diamonds').eq('id',user.id).maybeSingle();if(r.error){$('diamondBalance').textContent='—';return}$('diamondBalance').textContent=Number(r.data?.diamonds||0).toLocaleString('id-ID')}
async function loadScores(){if(!user){$('scores').innerHTML='<div class="empty">Login untuk melihat history.</div>';return}const games=['Quick Tap','Quiz'];const results=await Promise.all(games.map(game=>sb.from('game_scores').select('id,game,score,played_at').eq('user_id',user.id).eq('game',game).order('score',{ascending:false}).order('played_at',{ascending:false}).limit(1)));const failed=results.find(r=>r.error);if(failed){$('scores').innerHTML='<div class="empty">Gagal memuat score.<br><small>'+esc(failed.error.message)+'</small></div>';return}const best=results.map(r=>r.data?.[0]).filter(Boolean);best.sort((a,b)=>{const sa=Number(a.score||0),sb=Number(b.score||0);if(sb!==sa)return sb-sa;return new Date(b.played_at)-new Date(a.played_at)});$('scores').innerHTML=best.length?best.map(x=>`<div class="item"><div class="thumb">◇</div><div class="main"><b>${esc(x.game)}</b><small>${x.score} · ${new Date(x.played_at).toLocaleString('id-ID')}</small></div></div>`).join(''):'<div class="empty">Belum ada score.</div>'}
async function loadHomeChampion(){const box=$('homeChampion');if(!box)return;if(!user||!sb){box.innerHTML='';return}box.innerHTML='<div class="champion-card"><div class="champion-kicker">👑 Champion Spotlight · Quick Tap</div><div class="empty" style="margin-top:10px">Memuat juara #1…</div></div>';try{let r=await sb.rpc('get_leaderboard',{p_game:'Quick Tap'});if(r.error)throw r.error;if(!Array.isArray(r.data)||!r.data.length){box.innerHTML='';return}let x=r.data[0];let avatar='';if(x.avatar_path){let u=await sb.storage.from('avatars').createSignedUrl(x.avatar_path,900);if(u.data?.signedUrl)avatar='<img src="'+u.data.signedUrl+(u.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'" alt="Profile juara 1">'}let score=Number(x.score||0);let title=score>=100?'Sang Kilat Abadi':score>=90?'Si Cepat Kilat':score>=75?'Tangan Petir':score>=60?'Refleks Cahaya':'Pemburu Kecepatan';let diamondBalance=null;try{let dr=await sb.rpc('get_player_diamonds',{p_user_id:x.user_id});if(!dr.error&&Array.isArray(dr.data)&&dr.data.length)diamondBalance=Number(dr.data[0].diamond_balance||0)}catch(e){console.warn('Champion diamond:',e)}let diamondText=diamondBalance===null?'💎 —':`💎 ${diamondBalance.toLocaleString('id-ID')}`;box.innerHTML=`<section class="champion-card" aria-label="Juara 1 Quick Tap"><div class="champion-kicker">👑 Champion Spotlight · Quick Tap</div><div class="champion-layout"><div class="champion-avatar-wrap"><div class="champion-crown">👑</div><div class="champion-avatar"><div class="avatar-core">${avatar||esc((x.display_name||'L')[0].toUpperCase())}</div></div></div><div class="champion-copy"><div class="champion-title">JUARA #1 · ${esc(title)}</div><div class="champion-name ${nameEffectClass(x.equipped_name_effect_id)}">${nameEffectMarkup(x.display_name||'Lexiaa User',x.equipped_name_effect_id)}</div><div class="champion-subtitle">Pemegang score tertinggi Quick Tap di Lexiaa. Kecepatan yang layak dipajang.</div><div class="champion-stats"><div class="champion-score"><span class="champion-score-main">⚡ ${score} TAP</span><span class="champion-score-meta">dalam 10 detik</span></div><div class="champion-diamonds"><span class="diamond-icon">💎</span><span class="diamond-count">${diamondBalance===null?'—':diamondBalance.toLocaleString('id-ID')}</span></div></div></div><div class="champion-badge">TOP PLAYER</div></div></section>`}catch(e){box.innerHTML='<div class="champion-card"><div class="champion-kicker">👑 Champion Spotlight · Quick Tap</div><div class="empty" style="margin-top:10px">Champion belum dapat dimuat.</div></div>';console.error('Champion Spotlight:',e)}} 
async function loadLeaderboard(){if(!$('leaderboard'))return;if(!user){$('leaderboard').innerHTML='<div class="empty">Login untuk melihat leaderboard.</div>';return}let game=$('leaderGame')?.value||'Quick Tap';let r=await sb.rpc('get_leaderboard',{p_game:game});if(r.error){$('leaderboard').innerHTML='<div class="empty">Gagal memuat leaderboard.<br><small>'+esc(r.error.message)+'</small></div>';return}if(!r.data.length){$('leaderboard').innerHTML='<div class="empty">Belum ada score untuk '+esc(game)+'.</div>';return}let rows='';for(let i=0;i<r.data.length;i++){let x=r.data[i];let rank=i+1;let avatar='';if(x.avatar_path){let u=await sb.storage.from('avatars').createSignedUrl(x.avatar_path,900);if(u.data?.signedUrl)avatar='<img src="'+u.data.signedUrl+(u.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'" alt="Profile">'}let cls=rank<=3?' rank-'+rank:'';let crown=rank===1?'<span class="leader-crown" aria-label="Juara 1">👑</span>':'';let fallback=rank<=3?String(rank):String(rank);rows+=`<div class="item leader-item${cls}"><div class="leader-rank${cls}">${fallback}</div><div class="leader-profile">${crown}<div class="leader-avatar"><div class="avatar-core">${avatar||'<span class="rank-num">'+rank+'</span>'}</div></div></div><div class="main"><b class="${nameEffectClass(x.equipped_name_effect_id)}">${nameEffectMarkup(x.display_name||'Lexiaa User',x.equipped_name_effect_id)}</b><small>${esc(x.game)} · ${x.score} · ${new Date(x.played_at).toLocaleString('id-ID')}</small></div></div>`}$('leaderboard').innerHTML=rows}

const ETERNAL_FLOW_EFFECTS=new Set(['eternal_inferno','eternal_thunder','eternal_cryo','eternal_aqua','eternal_storm','eternal_cosmic','eternal_void','eternal_apocalypse']);
function nameEffectClass(id){return id?'name-effect-'+String(id).replace(/[^a-zA-Z0-9_-]/g,''):''}
function nameEffectMarkup(name,id){
  const safe=esc(name??'');
  if(!ETERNAL_FLOW_EFFECTS.has(String(id||''))) return safe;
  return Array.from(String(name??'')).map((ch,i)=>`<span class="flow-char" style="--flow-i:${i}">${ch===' '? '&nbsp;' : esc(ch)}</span>`).join('');
}
async function openShop(){
  if(!user)return openAuth();
  $('shopBody').innerHTML='<div class="empty">Memuat name effect shop…</div>';
  $('shopModal').classList.add('show');
  let [e,u,p]=await Promise.all([
    sb.from('profile_name_effects').select('*').order('sort_order',{ascending:true}),
    sb.from('user_profile_name_effects').select('effect_id').eq('user_id',user.id),
    sb.from('profiles').select('diamonds,display_name,equipped_name_effect_id').eq('id',user.id).maybeSingle()
  ]);
  if(e.error){$('shopBody').innerHTML='<div class="empty">Gagal memuat shop.<br><small>'+esc(e.error.message)+'</small></div>';return}
  let owned=new Set((u.data||[]).map(x=>x.effect_id)),prof=p.data||{};
  let sample=esc(prof.display_name||'Lexiaa User');
  let cards=(e.data||[]).map(x=>{
    let own=owned.has(x.id),equipped=prof.equipped_name_effect_id===x.id;
    let preview='<span class="effect-preview-name '+nameEffectClass(x.id)+'">'+nameEffectMarkup(prof.display_name||'Lexiaa User',x.id)+'</span>';
    let action=equipped
      ? '<button class="btn" onclick="equipNameEffect(null)">Lepas Efek</button>'
      : own
        ? '<button class="btn primary" onclick="equipNameEffect(\''+esc(x.id)+'\')">Pakai Efek</button>'
        : '<button class="btn primary" onclick="buyNameEffect(\''+esc(x.id)+'\')">💎 '+Number(x.price||0).toLocaleString('id-ID')+' · Beli</button>';
    return '<div class="effect-card"><div class="effect-preview">'+preview+'</div><div class="effect-name">'+esc(x.name)+'</div><div class="effect-desc">'+esc(x.description||'')+'</div><div class="effect-price '+(own?'effect-owned':'')+'">'+(own?'✓ Dimiliki':'💎 '+Number(x.price||0).toLocaleString('id-ID'))+'</div>'+action+'</div>';
  }).join('');
  $('shopBody').innerHTML='<div class="shop-hero"><div><div class="ey">NAME COSMETICS</div><div class="shop-balance">💎 '+Number(prof.diamonds||0).toLocaleString('id-ID')+'</div></div><span class="tag">Private collection</span></div><div class="effect-grid">'+(cards||'<div class="empty">Belum ada efek nama.</div>')+'</div><div class="shop-note">Efek nama hanya mengubah tampilan nama akun. Foto profil tetap bulat tanpa border.</div>';
}
function closeShop(){$('shopModal').classList.remove('show')}
async function buyNameEffect(id){
  if(!user)return openAuth();
  let r=await sb.rpc('buy_name_effect',{p_effect_id:id});
  if(r.error)return msg(r.error.message);
  msg('Efek nama berhasil dibeli');
  await openShop();await profile();await loadLeaderboard();await loadHomeChampion();
}
async function equipNameEffect(id){
  if(!user)return openAuth();
  let r=await sb.rpc('equip_name_effect',{p_effect_id:id});
  if(r.error)return msg(r.error.message);
  msg(id?'Efek nama dipasang':'Efek nama dilepas');
  closeShop();
  await profile();await avatar();await loadLeaderboard();await loadHomeChampion();
}
async function profile(){
  if(!user){$('profileCard').innerHTML='<div class="empty">Belum login.<br><button class="btn primary" style="margin-top:10px" onclick="openAuth()">Login / Daftar</button></div>';return}
  await ensure();
  let r=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle(),p=r.data||{};
  let av='';
  if(p.avatar_path){let u=await sb.storage.from('avatars').createSignedUrl(p.avatar_path,900);if(u.data?.signedUrl)av='<img src="'+u.data.signedUrl+(u.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'">'}
  let effect=nameEffectClass(p.equipped_name_effect_id);
  let display=esc(p.display_name||'Lexiaa User');
  $('profileCard').innerHTML='<div class="profile-shell"><div class="profile"><div class="avatar-core">'+(av||'<span class="avatar-fallback">'+esc((p.display_name||'L')[0])+'</span>')+'</div></div></div><div style="text-align:center"><h3 class="'+effect+'">'+nameEffectMarkup(p.display_name||'Lexiaa User',p.equipped_name_effect_id)+'</h3><div style="color:var(--m);font-size:12px">'+esc(user.email||'')+'</div></div><div class="profile-shop-actions"><button class="btn primary" onclick="openShop()">✨ Name Effect Shop</button><button class="btn" onclick="setAvatar()">Pasang/Ganti Foto</button></div><div class="form" style="margin-top:16px"><label>Nama tampilan<input id="displayName" value="'+display+'" maxlength="80"></label><label>Tema<select id="theme" style="width:100%;margin-top:5px;background:#0b0f18;border:1px solid var(--b);color:var(--t);padding:11px;border-radius:10px"><option value="obsidian" '+(p.theme==='obsidian'?'selected':'')+'>Obsidian</option><option value="midnight" '+(p.theme==='midnight'?'selected':'')+'>Midnight</option><option value="aurora" '+(p.theme==='aurora'?'selected':'')+'>Aurora</option></select></label><button class="btn primary" onclick="saveProfile()">Simpan profil</button></div><div style="display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:12px"><span class="tag">💎 '+Number(p.diamonds||0).toLocaleString('id-ID')+' diamond</span><button class="btn danger" onclick="logout()">Logout</button></div>';
  applyTheme(p.theme);
}
async function saveProfile(){let name=$('displayName').value.trim(),theme=$('theme').value;if(!name)return msg('Nama tidak boleh kosong');let r=await sb.from('profiles').update({display_name:name,theme,updated_at:new Date().toISOString()}).eq('id',user.id);if(r.error)return msg(r.error.message);applyTheme(theme);await avatar();msg('Profil disimpan');profile()}
function applyTheme(theme){document.documentElement.dataset.theme=theme||'obsidian'}
function setAvatar(){let i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=async()=>{let f=i.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return msg('File harus berupa gambar');if(f.size>8*1024*1024)return msg('Ukuran foto maksimal 8 MB');msg('Uploading profile…');let old=(await sb.from('profiles').select('avatar_path').eq('id',user.id).maybeSingle()).data?.avatar_path;let ext=(f.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').toLowerCase()||'jpg';let path=user.id+'/'+crypto.randomUUID()+'.'+ext;let u=await sb.storage.from('avatars').upload(path,f,{contentType:f.type,upsert:false,cacheControl:'3600'});if(u.error)return msg('Upload foto gagal: '+u.error.message);let d=await sb.from('profiles').update({avatar_path:path,updated_at:new Date().toISOString()}).eq('id',user.id);if(d.error){await sb.storage.from('avatars').remove([path]);return msg('Foto ter-upload tetapi profil gagal diperbarui: '+d.error.message)}if(old)await sb.storage.from('avatars').remove([old]);await avatar();await profile();msg('Foto profil berhasil disimpan')};i.click()}
async function logout(){await sb.auth.signOut();msg('Logout berhasil')}
window.addEventListener('load',()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');init();setTimeout(()=>loadHomeChampion(),1200)});
