// LEXIAA V19 - avatar render wrappers preserved from verified V18 build.

let sb=null,session=null,user=null;
const $=x=>document.getElementById(x);
function msg(x){$('toast').textContent=x;$('toast').classList.add('show');clearTimeout(window.tm);window.tm=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function page(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='home')loadHomeChampion();document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('on',(b?x===b:x.dataset.page===id)));if(id==='photos')loadPhotos();if(id==='music')loadMusic();if(id==='games'){loadScores();loadLeaderboard();loadWallet();}if(id==='profile')profile();if(id==='admin'&&adminUnlocked){loadAdminUsers();loadAdminVouchers()}scrollTo(0,0)}
function openM(t,b){$('mt').textContent=t;$('mb').innerHTML=b;$('modal').classList.add('show')}function closeM(){$('modal').classList.remove('show')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function authFeature(target){if(!user)return openAuth();page(target==='Games'?'games':'ai')}
function openAuth(){openM('Login / Daftar',`<form class="form" onsubmit="login(event)"><label>Email<input name="e" type="email" required></label><label>Password<input name="p" type="password" required minlength="6"></label><button class="btn primary">Login</button><button type="button" class="btn" onclick="signupForm()">Daftar akun baru</button></form>`)}
function signupForm(){openM('Daftar',`<form class="form" onsubmit="signup(event)"><label>Nama<input name="n" required></label><label>Email<input name="e" type="email" required></label><label>Password<input name="p" type="password" required minlength="6"></label><button class="btn primary">Daftar</button></form>`)}
async function login(e){e.preventDefault();let f=new FormData(e.target),r=await sb.auth.signInWithPassword({email:f.get('e'),password:f.get('p')});if(r.error)return msg(r.error.message);closeM();msg('Login berhasil')}
async function signup(e){e.preventDefault();let f=new FormData(e.target),email=f.get('e');let r=await sb.auth.signUp({email,password:f.get('p'),options:{data:{display_name:f.get('n')}}});if(r.error){let m=r.error.message||'';if(/rate limit|email rate limit|too many/i.test(m))return msg('Pendaftaran email sedang dibatasi Supabase. Tunggu beberapa menit atau gunakan email lain.');return msg(m)}closeM();msg(r.data.session?'Akun dibuat.':'Cek email untuk konfirmasi.')}
async function init(){let c=window.LEXIAA_CONFIG||{};if(!c.SUPABASE_URL||!c.SUPABASE_PUBLISHABLE_KEY){profile();return}sb=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY);let r=await sb.auth.getSession();apply(r.data.session);sb.auth.onAuthStateChange((_e,s)=>apply(s))}
async function apply(s){session=s;user=s?.user||null;profile();avatar();loadHomeChampion();if(document.querySelector('#photos.active'))loadPhotos();if(document.querySelector('#music.active'))loadMusic();if(document.querySelector('#games.active')){loadScores();loadLeaderboard();loadWallet()}}
async function ensure(){if(!user)return;let r=await sb.from('profiles').select('id').eq('id',user.id).maybeSingle();if(!r.data)await sb.from('profiles').insert({id:user.id,display_name:user.user_metadata?.display_name||user.email.split('@')[0]})}
async function avatar(){if(!user){$('ava').className='ava';$('ava').innerHTML='L';return}await ensure();let r=await sb.from('profiles').select('avatar_path,display_name,equipped_profile_aura_id').eq('id',user.id).maybeSingle();let el=$('ava');el.className='ava';let av='';if(r.data?.avatar_path){let u=await sb.storage.from('avatars').createSignedUrl(r.data.avatar_path,3600);if(!u.error&&u.data?.signedUrl)av='<img alt="Profile" src="'+u.data.signedUrl+(u.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'">'}el.innerHTML=decoratedAvatarMarkup(av,null,r.data?.equipped_profile_aura_id,(r.data?.display_name||'L')[0].toUpperCase());}
function addPhoto(){if(!user)return openAuth();$('pi').value='';$('pi').click()}$('pi').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;msg('Uploading…');let path=user.id+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');let u=await sb.storage.from('photos').upload(path,f,{contentType:f.type,upsert:false});if(u.error)return msg(u.error.message);let d=await sb.from('photos').insert({user_id:user.id,storage_path:path,file_name:f.name});if(d.error){await sb.storage.from('photos').remove([path]);return msg(d.error.message)}msg('Foto ditambahkan');loadPhotos()}
async function loadPhotos(){if(!user){$('photoList').innerHTML='<div class="empty">Login untuk melihat album.</div>';return}let r=await sb.from('photos').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(r.error){$('photoList').innerHTML='<div class="empty">Gagal memuat foto.<br><small>'+esc(r.error.message)+'</small></div>';return}if(!r.data.length){$('photoList').innerHTML='<div class="empty">Belum ada foto.</div>';return}let out='';for(let x of r.data){let u=await sb.storage.from('photos').createSignedUrl(x.storage_path,3600);let signed=u.data?.signedUrl||'';let safePath=encodeURIComponent(x.storage_path);let safeName=encodeURIComponent(x.file_name);out+=`<div class="item photo-item" onclick="openPhotoByPath('${safePath}','${safeName}')" style="cursor:zoom-in"><div class="thumb">${signed?'<img src="'+signed+(signed.includes('?')?'&':'?')+'v='+Date.now()+'" alt="'+esc(x.file_name)+'">':'◌'}</div><div class="main"><b>${esc(x.file_name)}</b><small>${new Date(x.created_at).toLocaleString('id-ID')} · Ketuk untuk buka & zoom</small></div><button class="btn" onclick="event.stopPropagation();openPhotoByPath('${safePath}','${safeName}')">⌕</button><button class="btn" onclick="event.stopPropagation();dl('${safePath}')">↓</button><button class="btn danger" onclick="event.stopPropagation();delPhoto('${x.id}','${safePath}')">×</button></div>`}$('photoList').innerHTML=out} 
async function openPhotoByPath(path,name){if(!user)return openAuth();let p=decodeURIComponent(path),n=decodeURIComponent(name||'Photo');let u=await sb.storage.from('photos').createSignedUrl(p,3600);if(u.error||!u.data?.signedUrl)return msg('Foto tidak dapat dibuka: '+(u.error?.message||'signed URL gagal'));openPhoto(encodeURIComponent(u.data.signedUrl),encodeURIComponent(n))}
let photoZoom=1,photoX=0,photoY=0,photoStartDist=0,photoStartZoom=1,photoDrag=false,photoLastX=0,photoLastY=0;
function openPhoto(encodedUrl,name){if(!encodedUrl)return msg('Preview foto tidak tersedia');let img=$('photoViewerImg');img.src=decodeURIComponent(encodedUrl);$('photoTitle').textContent=decodeURIComponent(name||'Photo');photoZoom=1;photoX=0;photoY=0;applyPhotoTransform();$('photoModal').classList.add('show')}
function closePhoto(){$('photoModal').classList.remove('show');$('photoViewerImg').src=''}
function applyPhotoTransform(){let img=$('photoViewerImg');img.style.transform=`translate3d(${photoX}px,${photoY}px,0) scale(${photoZoom})`}
function zoomPhoto(delta){photoZoom=Math.min(5,Math.max(1,photoZoom+delta));if(photoZoom===1){photoX=0;photoY=0}applyPhotoTransform()}
function resetPhotoZoom(){photoZoom=1;photoX=0;photoY=0;applyPhotoTransform()}
$('photoViewerImg').addEventListener('dblclick',()=>zoomPhoto(photoZoom>1?-1:1));
$('photoStage').addEventListener('wheel',e=>{e.preventDefault();zoomPhoto(e.deltaY<0?0.2:-0.2)},{passive:false});
$('photoStage').addEventListener('touchstart',e=>{if(e.touches.length===2){photoStartDist=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);photoStartZoom=photoZoom}else if(e.touches.length===1&&photoZoom>1){photoDrag=true;photoLastX=e.touches[0].clientX;photoLastY=e.touches[0].clientY}}, {passive:true});
$('photoStage').addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();let d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);photoZoom=Math.min(5,Math.max(1,photoStartZoom*(d/photoStartDist)));applyPhotoTransform()}else if(e.touches.length===1&&photoDrag&&photoZoom>1){e.preventDefault();let dx=e.touches[0].clientX-photoLastX,dy=e.touches[0].clientY-photoLastY;photoLastX=e.touches[0].clientX;photoLastY=e.touches[0].clientY;photoX+=dx;photoY+=dy;applyPhotoTransform()}},{passive:false});
$('photoStage').addEventListener('touchend',e=>{if(e.touches.length===0)photoDrag=false});
async function dl(p){let r=await sb.storage.from('photos').download(decodeURIComponent(p));if(r.error)return msg(r.error.message);let u=URL.createObjectURL(r.data),a=document.createElement('a');a.href=u;a.download=decodeURIComponent(p).split('/').pop();a.click();URL.revokeObjectURL(u)}
async function delPhoto(id,p){if(!confirm('Hapus foto?'))return;let r=await sb.from('photos').delete().eq('id',id).eq('user_id',user.id);if(r.error)return msg(r.error.message);await sb.storage.from('photos').remove([decodeURIComponent(p)]);loadPhotos()}
function addMusic(){if(!user)return openAuth();$('mi').value='';$('mi').click()}$('mi').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;msg('Uploading…');let path=user.id+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');let u=await sb.storage.from('music').upload(path,f,{contentType:f.type,upsert:false});if(u.error)return msg(u.error.message);let d=await sb.from('music').insert({user_id:user.id,storage_path:path,title:f.name});if(d.error){await sb.storage.from('music').remove([path]);return msg(d.error.message)}msg('Musik ditambahkan');loadMusic()}
async function loadMusic(){if(!user){$('musicList').innerHTML='<div class="empty">Login untuk melihat musik.</div>';return}let r=await sb.from('music').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(r.error)return $('musicList').innerHTML='<div class="empty">'+esc(r.error.message)+'</div>';if(!r.data.length)return $('musicList').innerHTML='<div class="empty">Belum ada musik.</div>';let out='';for(let x of r.data){let u=await sb.storage.from('music').createSignedUrl(x.storage_path,900);out+=`<div class="item"><div class="thumb">♪</div><div class="main"><b>${esc(x.title)}</b>${u.data?.signedUrl?'<audio controls preload="none" style="width:100%;margin-top:6px" src="'+u.data.signedUrl+'"></audio>':''}</div><button class="btn" onclick="dlMusic('${encodeURIComponent(x.storage_path)}','${encodeURIComponent(x.title)}')">↓</button><button class="btn danger" onclick="delMusic('${x.id}','${encodeURIComponent(x.storage_path)}')">×</button></div>`}$('musicList').innerHTML=out}
async function dlMusic(p,name){let r=await sb.storage.from('music').download(decodeURIComponent(p));if(r.error)return msg(r.error.message);let u=URL.createObjectURL(r.data),a=document.createElement('a');a.href=u;a.download=decodeURIComponent(name||p).split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function delMusic(id,p){if(!confirm('Hapus musik?'))return;let r=await sb.from('music').delete().eq('id',id).eq('user_id',user.id);if(r.error)return msg(r.error.message);let st=await sb.storage.from('music').remove([decodeURIComponent(p)]);if(st.error)return msg('Database terhapus, tetapi file gagal dihapus: '+st.error.message);msg('Musik dihapus');loadMusic()}
function ai(tool){if(!user)return openAuth();openM('AI '+tool,'<div class="empty">AI tool siap. Provider AI dapat disambungkan melalui backend tanpa menaruh secret key di frontend.</div>')}
let tapScore=0,tapStart=0,tapTimer=null;const quiz=[['Apa fungsi utama RLS di Supabase?',['Mengatur akses data berdasarkan policy','Mengompres gambar','Mengubah password'],0],['Format audio yang umum di web adalah…',['MP3','PSD','SVG'],0],['Secret/service_role key seharusnya disimpan di…',['Backend/Edge Function','HTML frontend','CSS'],0]];
function game(name){if(!user)return openAuth();if(name==='Quick Tap')startTap();else startQuiz()}
function startTap(){openM('Quick Tap',`<div class="empty">Tap sebanyak mungkin dalam 10 detik.</div><button class="btn primary" style="margin-top:10px;width:100%;height:90px;font-size:28px" onclick="beginTap()">Mulai</button>`)}
function beginTap(){tapScore=0;tapStart=Date.now();openM('Quick Tap',`<div class="empty"><b id="tapTime">10.0</b> detik · Score <b id="tapScore">0</b></div><button class="btn primary" style="margin-top:10px;width:100%;height:120px;font-size:30px" onclick="tap()">TAP!</button>`);clearInterval(tapTimer);tapTimer=setInterval(()=>{let left=10-(Date.now()-tapStart)/1000;let t=$('tapTime');if(t)t.textContent=Math.max(0,left).toFixed(1);if(left<=0){clearInterval(tapTimer);finishTap()}},100)}
function tap(){if(Date.now()-tapStart>=10000)return;tapScore++;let e=$('tapScore');if(e)e.textContent=tapScore}
function finishTap(){openM('Quick Tap — Selesai',`<div class="empty">Score: <b>${tapScore}</b></div><button class="btn primary" style="margin-top:10px" onclick="saveScore('Quick Tap',${tapScore})">Simpan score</button>`)}
let qi=0,qc=0;
function startQuiz(){qi=0;qc=0;showQ()}
function showQ(){if(qi>=quiz.length)return finishQuiz();let q=quiz[qi];openM('Quiz',`<div style="color:var(--m);font-size:12px">Pertanyaan ${qi+1}/${quiz.length}</div><h3>${esc(q[0])}</h3><div class="form">${q[1].map((a,i)=>`<button class="btn" onclick="answerQ(${i})">${esc(a)}</button>`).join('')}</div>`)}
function answerQ(i){if(i===quiz[qi][2])qc++;qi++;showQ()}
function finishQuiz(){let score=qc*100;openM('Quiz — Selesai',`<div class="empty">Benar: <b>${qc}/${quiz.length}</b><br>Score: <b>${score}</b></div><button class="btn primary" style="margin-top:10px" onclick="saveScore('Quiz',${score})">Simpan score</button>`)}
async function saveScore(game,score){if(!user)return openAuth();let r=await sb.rpc('save_game_score',{p_game:game,p_score:Math.max(0,Math.floor(score))});if(r.error)return msg('Gagal menyimpan score: '+r.error.message);let result=Array.isArray(r.data)?r.data[0]:r.data;closeM();await loadScores();await loadLeaderboard();await loadWallet();let earned=Number(result?.diamonds_earned||0);await loadHomeChampion();msg(earned>0?`Score tersimpan · +${earned} 💎`:'Score tersimpan')}
async function loadWallet(){if(!$('diamondBalance'))return;if(!user){$('diamondBalance').textContent='0';return}let r=await sb.from('profiles').select('diamonds').eq('id',user.id).maybeSingle();if(r.error){$('diamondBalance').textContent='—';return}$('diamondBalance').textContent=Number(r.data?.diamonds||0).toLocaleString('id-ID')}
async function loadScores(){if(!user){$('scores').innerHTML='<div class="empty">Login untuk melihat history.</div>';return}const games=['Quick Tap','Quiz'];const results=await Promise.all(games.map(game=>sb.from('game_scores').select('id,game,score,played_at').eq('user_id',user.id).eq('game',game).order('score',{ascending:false}).order('played_at',{ascending:false}).limit(1)));const failed=results.find(r=>r.error);if(failed){$('scores').innerHTML='<div class="empty">Gagal memuat score.<br><small>'+esc(failed.error.message)+'</small></div>';return}const best=results.map(r=>r.data?.[0]).filter(Boolean);best.sort((a,b)=>{const sa=Number(a.score||0),sb=Number(b.score||0);if(sb!==sa)return sb-sa;return new Date(b.played_at)-new Date(a.played_at)});$('scores').innerHTML=best.length?best.map(x=>`<div class="item"><div class="thumb">◇</div><div class="main"><b>${esc(x.game)}</b><small>${x.score} · ${new Date(x.played_at).toLocaleString('id-ID')}</small></div></div>`).join(''):'<div class="empty">Belum ada score.</div>'}
async function getCosmetics(ids){const map=new Map();const clean=[...new Set((ids||[]).filter(Boolean))];if(!clean.length)return map;const r=await sb.from('profiles').select('id,equipped_profile_aura_id').in('id',clean);if(r.error){console.warn('Profile cosmetics:',r.error);return map}(r.data||[]).forEach(x=>map.set(x.id,x));return map}
function decoratedAvatarMarkup(avatarHtml,sparkId,auraId,fallback){const a=String(auraId||'');const s=String(sparkId||'');const safe=esc(fallback||'L');const aura=a?'<span class="decor-aura aura-'+a+'"></span>':'';let spark='';if(s){const angles=s==='blackhole'?[0,60,120,180,240,300]:[0,72,144,216,288];spark='<span class="decor-spark spark-'+s+'">'+angles.map((a,i)=>'<i class="spark-particle" style="--a:'+a+'deg;--spark-delay:'+(i*.35).toFixed(2)+'s"></i>').join('')+'</span>'}return '<span class="avatar-decor">'+aura+spark+'<span class="decor-avatar-core">'+(avatarHtml||safe)+'</span></span>'}
function nameEffectClass(id){return id?'name-effect-'+String(id).replace(/[^a-zA-Z0-9_-]/g,''):''}
const ETERNAL_FLOW_EFFECTS=new Set(['eternal_inferno','eternal_thunder','eternal_cryo','eternal_aqua','eternal_storm','eternal_cosmic','eternal_void','eternal_apocalypse']);
function nameEffectMarkup(name,id){
  const safe=String(name??'');
  if(!ETERNAL_FLOW_EFFECTS.has(String(id||''))) return esc(safe);
  return Array.from(safe).map((ch,i)=>`<span class="flow-char" style="--flow-i:${i}">${ch===' '? '&nbsp;' : esc(ch)}</span>`).join('');
}

async function openShop(){
  if(!user)return openAuth();
  $('shopBody').innerHTML='<div class="empty">Memuat name effect shop…</div>';
  $('shopModal').classList.add('show');
  let [e,u,p]=await Promise.all([
    sb.from('profile_name_effects').select('*').order('sort_order',{ascending:true}),
    sb.from('user_profile_name_effects').select('effect_id').eq('user_id',user.id),
    sb.from('profiles').select('diamonds,display_name,equipped_name_effect_id').eq('id',user.id).maybeSingle()
  ]);
  if(e.error){$('shopBody').innerHTML='<div class="empty">Gagal memuat shop.<br><small>'+esc(e.error.message)+'</small></div>';return}
  if(p.error){$('shopBody').innerHTML='<div class="empty">Gagal memuat saldo.<br><small>'+esc(p.error.message)+'</small></div>';return}
  let owned=new Set((u.data||[]).map(x=>x.effect_id)),prof=p.data||{};
  let cards=(e.data||[]).map(x=>{
    let own=owned.has(x.id),equipped=prof.equipped_name_effect_id===x.id;
    let preview='<span class="effect-preview-name '+nameEffectClass(x.id)+'">'+nameEffectMarkup(prof.display_name||'Lexiaa User',x.id)+'</span>';
    let action=equipped
      ? '<button class="btn" onclick="equipNameEffect(null)">Lepas Efek</button>'
      : own
        ? '<button class="btn primary" onclick="equipNameEffect(\''+esc(x.id)+'\')">Pakai Efek</button>'
        : '<button class="btn primary" onclick="buyNameEffect(\''+esc(x.id)+'\')">💎 '+Number(x.price||0).toLocaleString('id-ID')+' · Beli</button>';
    return '<div class="effect-card"><div class="effect-preview">'+preview+'</div><div class="effect-name">'+esc(x.name)+'</div><div class="effect-desc">'+esc(x.description||'')+'</div><div class="effect-price '+(own?'effect-owned':'')+'">'+(own?'✓ Dimiliki':'💎 '+Number(x.price||0).toLocaleString('id-ID'))+'</div>'+action+'</div>';
  }).join('');
  $('shopBody').innerHTML='<div class="shop-hero"><div><div class="ey">NAME COSMETICS</div><div class="shop-balance">💎 '+Number(prof.diamonds||0).toLocaleString('id-ID')+'</div></div><span class="tag">Private collection</span></div><div class="effect-grid">'+(cards||'<div class="empty">Belum ada efek nama.</div>')+'</div><div class="shop-note">Efek nama hanya mengubah tampilan nama akun. Foto profil tetap bulat tanpa border.</div>';
}
function closeShop(){$('shopModal').classList.remove('show')}
async function buyNameEffect(id){
  if(!user)return openAuth();
  let r=await sb.rpc('buy_name_effect',{p_effect_id:id});
  if(r.error)return msg(r.error.message);
  msg('Efek nama berhasil dibeli');
  await openShop();await profile();await loadLeaderboard();await loadHomeChampion();
}
async function equipNameEffect(id){
  if(!user)return openAuth();
  let r=await sb.rpc('equip_name_effect',{p_effect_id:id});
  if(r.error)return msg(r.error.message);
  msg(id?'Efek nama dipasang':'Efek nama dilepas');
  closeShop();
  await profile();await avatar();await loadLeaderboard();await loadHomeChampion();
}
async function loadHomeChampion(){const box=$('homeChampion');if(!box)return;if(!user||!sb){box.innerHTML='';return}box.innerHTML='<div class="champion-card"><div class="champion-kicker">👑 Champion Spotlight · Quick Tap</div><div class="empty" style="margin-top:10px">Memuat juara #1…</div></div>';try{let r=await sb.rpc('get_leaderboard',{p_game:'Quick Tap'});if(r.error)throw r.error;if(!Array.isArray(r.data)||!r.data.length){box.innerHTML='';return}let x=r.data[0],avatar='';if(x.avatar_path){let u=await sb.storage.from('avatars').createSignedUrl(x.avatar_path,900);if(u.data?.signedUrl)avatar='<img src="'+u.data.signedUrl+(u.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'" alt="Profile juara 1">'}let c=(await getCosmetics([x.user_id])).get(x.user_id)||{},score=Number(x.score||0),title=score>=100?'Sang Kilat Abadi':score>=90?'Si Cepat Kilat':score>=75?'Tangan Petir':score>=60?'Refleks Cahaya':'Pemburu Kecepatan',diamondBalance=null;try{let dr=await sb.rpc('get_player_diamonds',{p_user_id:x.user_id});if(!dr.error&&Array.isArray(dr.data)&&dr.data.length)diamondBalance=Number(dr.data[0].diamond_balance||0)}catch(e){}box.innerHTML='<section class="champion-card" aria-label="Juara 1 Quick Tap"><div class="champion-kicker">👑 Champion Spotlight · Quick Tap</div><div class="champion-layout"><div class="champion-avatar-wrap"><div class="champion-crown">👑</div><div class="champion-avatar">'+decoratedAvatarMarkup(avatar,null,c.equipped_profile_aura_id,esc((x.display_name||'L')[0].toUpperCase()))+'</div></div><div class="champion-copy"><div class="champion-title">JUARA #1 · '+esc(title)+'</div><div class="champion-name '+nameEffectClass(x.equipped_name_effect_id)+'">'+nameEffectMarkup(x.display_name||'Lexiaa User',x.equipped_name_effect_id)+'</div><div class="champion-subtitle">Pemegang score tertinggi Quick Tap di Lexiaa. Kecepatan yang layak dipajang.</div><div class="champion-stats"><div class="champion-score"><span class="champion-score-main">⚡ '+score+' TAP</span><span class="champion-score-meta">dalam 10 detik</span></div><div class="champion-diamonds"><span class="diamond-icon">💎</span><span class="diamond-count">'+(diamondBalance===null?'—':diamondBalance.toLocaleString('id-ID'))+'</span></div></div></div><div class="champion-badge">TOP PLAYER</div></div></section>'}catch(e){box.innerHTML='<div class="champion-card"><div class="champion-kicker">👑 Champion Spotlight · Quick Tap</div><div class="empty" style="margin-top:10px">Champion belum dapat dimuat.</div></div>';console.error('Champion Spotlight:',e)}}
async function loadLeaderboard(){if(!$('leaderboard'))return;if(!user){$('leaderboard').innerHTML='<div class="empty">Login untuk melihat leaderboard.</div>';return}let game=$('leaderGame')?.value||'Quick Tap';let r=await sb.rpc('get_leaderboard',{p_game:game});if(r.error){$('leaderboard').innerHTML='<div class="empty">Gagal memuat leaderboard.<br><small>'+esc(r.error.message)+'</small></div>';return}if(!r.data.length){$('leaderboard').innerHTML='<div class="empty">Belum ada score untuk '+esc(game)+'.</div>';return}let cosmetics=await getCosmetics(r.data.map(x=>x.user_id)),rows='';for(let i=0;i<r.data.length;i++){let x=r.data[i],rank=i+1,avatar='';if(x.avatar_path){let u=await sb.storage.from('avatars').createSignedUrl(x.avatar_path,900);if(u.data?.signedUrl)avatar='<img src="'+u.data.signedUrl+(u.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'" alt="Profile">'}let c=cosmetics.get(x.user_id)||{},cls=rank<=3?' rank-'+rank:'',crown=rank===1?'<span class="leader-crown" aria-label="Juara 1">👑</span>':'';rows+='<div class="item leader-item'+cls+'"><div class="leader-rank'+cls+'">'+rank+'</div><div class="leader-profile">'+crown+'<div class="leader-avatar">'+decoratedAvatarMarkup(avatar,null,c.equipped_profile_aura_id,'#'+rank)+'</div></div><div class="main"><b class="'+nameEffectClass(x.equipped_name_effect_id)+'">'+nameEffectMarkup(x.display_name||'Lexiaa User',x.equipped_name_effect_id)+'</b><small>'+esc(x.game)+' · '+x.score+' · '+new Date(x.played_at).toLocaleString('id-ID')+'</small></div></div>'}$('leaderboard').innerHTML=rows}
async function openAuraShop(){
  if(!user)return openAuth();
  $('auraBody').innerHTML='<div class="empty">Memuat Profile Aura Shop…</div>';
  $('auraModal').classList.add('show');
  let [e,u,p]=await Promise.all([
    sb.from('profile_auras').select('*').order('sort_order',{ascending:true}),
    sb.from('user_profile_auras').select('aura_id').eq('user_id',user.id),
    sb.from('profiles').select('diamonds,spark_saldo,display_name,avatar_path,equipped_profile_aura_id').eq('id',user.id).maybeSingle()
  ]);
  if(e.error){$('auraBody').innerHTML='<div class="empty">Gagal memuat Aura Shop.<br><small>'+esc(e.error.message)+'</small></div>';return}
  if(p.error){$('auraBody').innerHTML='<div class="empty">Gagal memuat saldo.<br><small>'+esc(p.error.message)+'</small></div>';return}
  let prof=p.data||{},owned=new Set((u.data||[]).map(x=>x.aura_id)),av='';
  if(prof.avatar_path){let au=await sb.storage.from('avatars').createSignedUrl(prof.avatar_path,900);if(au.data?.signedUrl)av='<img alt="Profile" src="'+au.data.signedUrl+(au.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'">'}
  let wallet='<div class="spark-exchange"><div class="ey">Premium Aura Currency</div><div class="spark-wallet"><div><small>💠 Spark Saldo</small><b>'+Number(prof.spark_saldo||0).toLocaleString('id-ID')+'</b></div><span class="tag">Dipakai untuk Aura</span></div><div class="card" style="padding:12px;margin:0"><div class="head"><div><b>💎 Tukar Diamond → 💠 Spark Saldo</b><small style="display:block;color:var(--m);margin-top:4px">Rate: 100 Diamond = 10 Spark Saldo. Tidak bisa ditukar balik.</small></div><span class="tag">💎 '+Number(prof.diamonds||0).toLocaleString('id-ID')+'</span></div><div class="exchange-row" style="margin-top:10px"><button class="btn primary" onclick="exchangeDiamondToSpark(100)">💎 100 → 💠 10</button><button class="btn primary" onclick="exchangeDiamondToSpark(500)">💎 500 → 💠 50</button><button class="btn primary" onclick="exchangeDiamondToSpark(1000)">💎 1.000 → 💠 100</button><button class="btn primary" onclick="exchangeDiamondToSpark(5000)">💎 5.000 → 💠 500</button></div></div></div>';
  let cards=(e.data||[]).map(x=>{let own=owned.has(x.id),equipped=prof.equipped_profile_aura_id===x.id,preview='<div class="aura-preview">'+decoratedAvatarMarkup(av,null,x.id,(prof.display_name||'Lexiaa User')[0])+'</div>',action=equipped?'<button class="btn" onclick="equipProfileAura(null)">Lepas Aura</button>':own?'<button class="btn primary" onclick="equipProfileAura(\''+esc(x.id)+'\')">Pakai Aura</button>':'<button class="btn primary" onclick="buyProfileAura(\''+esc(x.id)+'\')">💠 '+Number(x.price_saldo||0).toLocaleString('id-ID')+' · Beli</button>';return '<div class="aura-card">'+preview+'<div class="aura-name">'+esc(x.name)+'</div><div class="aura-desc">'+esc(x.description||'')+'</div><div class="aura-price '+(own?'aura-owned':'')+'">'+(own?'✓ Dimiliki':'💠 '+Number(x.price_saldo||0).toLocaleString('id-ID'))+'</div>'+action+'</div>'}).join('');
  $('auraBody').innerHTML=wallet+'<div class="effect-grid">'+(cards||'<div class="empty">Belum ada Profile Aura.</div>')+'</div><div class="aura-shop-note">Profile Aura adalah lapisan glow di belakang avatar. Pembayaran menggunakan Spark Saldo.</div>'
}
function openExchangeShop(){
  if(!user)return openAuth();
  const modal=$('exchangeModal');
  const body=$('exchangeBody');
  if(!modal||!body)return;
  body.innerHTML='<div class="spark-exchange"><div class="ey">Premium Currency</div><div class="card" style="padding:12px;margin:0"><div class="head"><div><b>💎 Tukar Diamond → 💠 Spark Saldo</b><small style="display:block;color:var(--m);margin-top:4px">Rate: 100 Diamond = 10 Spark Saldo. Tidak bisa ditukar balik.</small></div><span class="tag" id="exchangeDiamondBalance">💎 —</span></div><div class="exchange-row" style="margin-top:10px"><button class="btn primary" onclick="exchangeDiamondToSpark(100)">💎 100 → 💠 10</button><button class="btn primary" onclick="exchangeDiamondToSpark(500)">💎 500 → 💠 50</button><button class="btn primary" onclick="exchangeDiamondToSpark(1000)">💎 1.000 → 💠 100</button><button class="btn primary" onclick="exchangeDiamondToSpark(5000)">💎 5.000 → 💠 500</button></div></div><div class="spark-wallet" style="margin-top:10px"><div><small>💠 Spark Saldo</small><b id="exchangeSparkBalance">—</b></div><span class="tag">Dipakai untuk Profile Aura</span></div></div>';
  modal.classList.add('show');
  refreshExchangeBalances();
}
function closeExchangeShop(){$('exchangeModal').classList.remove('show')}
async function refreshExchangeBalances(){
  if(!user)return;
  let r=await sb.from('profiles').select('diamonds,spark_saldo').eq('id',user.id).maybeSingle();
  if(r.error)return;
  if($('exchangeDiamondBalance'))$('exchangeDiamondBalance').textContent='💎 '+Number(r.data?.diamonds||0).toLocaleString('id-ID');
  if($('exchangeSparkBalance'))$('exchangeSparkBalance').textContent=Number(r.data?.spark_saldo||0).toLocaleString('id-ID');
}

function closeAuraShop(){$('auraModal').classList.remove('show')}
async function exchangeDiamondToSpark(amount){
  if(!user)return openAuth();
  amount=Number(amount||0);
  if(!Number.isInteger(amount)||amount<=0||amount%100!==0)return msg('Jumlah Diamond harus kelipatan 100');
  let spark=Math.floor(amount/10);
  if(!confirm('Tukar '+amount.toLocaleString('id-ID')+' Diamond menjadi '+spark.toLocaleString('id-ID')+' Spark Saldo?\n\nPenukaran tidak bisa dibatalkan.'))return;
  let r=await sb.rpc('exchange_diamond_to_spark',{p_diamond_amount:amount});
  if(r.error)return msg(r.error.message);
  let row=Array.isArray(r.data)?r.data[0]:r.data;
  msg('Berhasil ditukar · 💠 '+Number(row?.new_spark_saldo||0).toLocaleString('id-ID')+' Spark Saldo');
  closeExchangeShop();
  await refreshExchangeBalances();
  await profile();
}
async function buyProfileAura(id){if(!user)return openAuth();let r=await sb.rpc('buy_profile_aura',{p_aura_id:id});if(r.error)return msg(r.error.message);msg('Profile Aura berhasil dibeli');await openAuraShop();await profile()}
async function equipProfileAura(id){if(!user)return openAuth();let r=await sb.rpc('equip_profile_aura',{p_aura_id:id});if(r.error)return msg(r.error.message);msg(id?'Profile Aura dipasang':'Profile Aura dilepas');closeAuraShop();await profile();await avatar()}
function diamondAuraClass(d){d=Number(d||0);if(d>=25000)return 'diamond-aura-eternal';if(d>=10000)return 'diamond-aura-mythic';if(d>=2500)return 'diamond-aura-celestial';if(d>=500)return 'diamond-aura-royal';if(d>=100)return 'diamond-aura-aqua';return 'diamond-aura-soft'}
async function profile(){
  const box=$('profileCard');
  if(!box)return;
  if(!user){box.innerHTML='<div class="empty">Belum login.<br><button class="btn primary" style="margin-top:10px" onclick="openAuth()">Login / Daftar</button></div>';return}
  try{
    await ensure();
    const r=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();
    if(r.error) throw r.error;
    const p=r.data||{};
    let av='';
    if(p.avatar_path){
      const u=await sb.storage.from('avatars').createSignedUrl(p.avatar_path,900);
      if(!u.error&&u.data?.signedUrl) av='<img alt="Profile" src="'+u.data.signedUrl+(u.data.signedUrl.includes('?')?'&':'?')+'v='+Date.now()+'">';
    }
    const effect=nameEffectClass(p.equipped_name_effect_id);
    const display=esc(p.display_name||'Lexiaa User');
    const avatarMarkup=decoratedAvatarMarkup(av,null,p.equipped_profile_aura_id,(p.display_name||'L')[0]);
    box.innerHTML=avatarMarkup+
      '<div style="text-align:center"><h3 class="'+effect+'">'+nameEffectMarkup(p.display_name||'Lexiaa User',p.equipped_name_effect_id)+'</h3><div style="color:var(--m);font-size:12px">'+esc(user.email||'')+'</div></div>'+
      '<div class="profile-shop-actions"><button class="btn primary" onclick="openShop()">✨ Name Effect Shop</button><button class="btn primary" onclick="openAuraShop()">🌌 Profile Aura Shop</button><button class="btn primary" onclick="openExchangeShop()">💎 Tukar Diamond</button><button class="btn" onclick="setAvatar()">Pasang/Ganti Foto</button></div>'+
      '<div style="display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:12px"><span class="tag diamond-aura '+diamondAuraClass(p.diamonds)+'"><span class="diamond-icon">💎</span> '+Number(p.diamonds||0).toLocaleString('id-ID')+' diamond</span><span class="spark-mini">💠 '+Number(p.spark_saldo||0).toLocaleString('id-ID')+' Spark Saldo</span></div>'+
      '<div class="form" style="margin-top:16px"><label>Nama tampilan<input id="displayName" value="'+display+'" maxlength="80"></label><label>Tema<select id="theme" style="width:100%;margin-top:5px;background:#0b0f18;border:1px solid var(--b);color:var(--t);padding:11px;border-radius:10px"><option value="obsidian" '+(p.theme==='obsidian'?'selected':'')+'>Obsidian</option><option value="midnight" '+(p.theme==='midnight'?'selected':'')+'>Midnight</option><option value="aurora" '+(p.theme==='aurora'?'selected':'')+'>Aurora</option></select></label><button class="btn primary" onclick="saveProfile()">Simpan profil</button></div>'+ 
      '<div style="display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="btn danger" onclick="logout()">Logout</button></div>';
    applyTheme(p.theme);
  }catch(e){
    console.error('Profile render:',e);
    box.innerHTML='<div class="empty">Profil gagal dimuat.<br><small>'+esc(e?.message||'Terjadi kesalahan saat memuat profil.')+'</small><br><button class="btn" style="margin-top:10px" onclick="profile()">Coba lagi</button></div>';
  }
}
async function saveProfile(){let name=$('displayName').value.trim(),theme=$('theme').value;if(!name)return msg('Nama tidak boleh kosong');let r=await sb.from('profiles').update({display_name:name,theme,updated_at:new Date().toISOString()}).eq('id',user.id);if(r.error)return msg(r.error.message);applyTheme(theme);await avatar();msg('Profil disimpan');profile()}
function applyTheme(theme){document.documentElement.dataset.theme=theme||'obsidian'}
function setAvatar(){let i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=async()=>{let f=i.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return msg('File harus berupa gambar');if(f.size>8*1024*1024)return msg('Ukuran foto maksimal 8 MB');msg('Uploading profile…');let old=(await sb.from('profiles').select('avatar_path').eq('id',user.id).maybeSingle()).data?.avatar_path;let ext=(f.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').toLowerCase()||'jpg';let path=user.id+'/'+crypto.randomUUID()+'.'+ext;let u=await sb.storage.from('avatars').upload(path,f,{contentType:f.type,upsert:false,cacheControl:'3600'});if(u.error)return msg('Upload foto gagal: '+u.error.message);let d=await sb.from('profiles').update({avatar_path:path,updated_at:new Date().toISOString()}).eq('id',user.id);if(d.error){await sb.storage.from('avatars').remove([path]);return msg('Foto ter-upload tetapi profil gagal diperbarui: '+d.error.message)}if(old)await sb.storage.from('avatars').remove([old]);await avatar();await profile();msg('Foto profil berhasil disimpan')};i.click()}
let adminKeySession='',adminUnlocked=false,adminSelectedUser=null;
function openAdminGate(){openM('Admin Panel',`<div class="empty">Panel ini hanya bisa dibuka dengan kata kunci admin.</div><form class="form" style="margin-top:12px" onsubmit="unlockAdmin(event)"><label>Kata kunci<input name="k" type="password" autocomplete="off" required></label><button class="btn primary">Masuk Admin Panel</button></form>`)}
async function unlockAdmin(e){e.preventDefault();if(!user)return openAuth();let key=String(new FormData(e.target).get('k')||'');if(!key)return msg('Masukkan kata kunci admin');let check=await sb.rpc('lexiaa_admin_check',{p_key:key});if(check.error||check.data!==true)return msg(check.error?.message||'Kata kunci admin salah');adminKeySession=key;adminUnlocked=true;closeM();page('admin');await loadAdminUsers();await loadAdminVouchers()}
function adminErr(r){return r?.error?.message||'Permintaan admin gagal'}
function randomVoucherCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let out='LEX-';for(let i=0;i<10;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out}
function openRedeemVoucher(){if(!user)return openAuth();openM('🎟️ Redeem Voucher',`<div class="empty" style="padding:18px 10px;margin-bottom:12px">Masukkan kode voucher Diamond dari admin. Setiap voucher hanya bisa dipakai sekali per akun.</div><form class="form" onsubmit="redeemVoucher(event)"><label>Kode Voucher<input name="code" maxlength="64" autocomplete="off" autocapitalize="characters" placeholder="Contoh: LEX-ABCD-1234" required></label><button class="btn primary">🎟️ Redeem Voucher</button></form>`)}
async function redeemVoucher(e){e.preventDefault();if(!user)return openAuth();let code=String(new FormData(e.target).get('code')||'').trim();if(!code)return msg('Masukkan kode voucher');let r=await sb.rpc('redeem_diamond_voucher',{p_code:code});if(r.error)return msg(r.error.message||'Voucher gagal diredeem');let x=Array.isArray(r.data)?r.data[0]:r.data;closeM();await loadWallet();msg(`Voucher berhasil · +${Number(x?.diamond_reward||0).toLocaleString('id-ID')} 💎`)}
async function loadAdminVouchers(){if(!adminUnlocked)return;let box=$('adminVouchers');if(!box)return;box.innerHTML='<div class="empty">Memuat voucher...</div>';let r=await sb.rpc('lexiaa_admin_list_vouchers',{p_key:adminKeySession});if(r.error){box.innerHTML='<div class="empty">Gagal memuat voucher.<br><small>'+esc(adminErr(r))+'</small></div>';return}if(!r.data?.length){box.innerHTML='<div class="empty">Belum ada voucher.</div>';return}box.innerHTML=r.data.map(v=>{let exhausted=Number(v.redeemed_count)>=Number(v.max_redemptions);let active=!!v.active&&!exhausted;let status=exhausted?'<span class="admin-status banned">HABIS</span>':active?'<span class="admin-status">AKTIF</span>':'<span class="admin-status banned">NONAKTIF</span>';return `<div class="item admin-voucher"><div class="main"><b>🎟️ ${esc(v.code)}</b><small>💎 ${Number(v.diamond_reward||0).toLocaleString('id-ID')} · ${Number(v.redeemed_count||0)}/${Number(v.max_redemptions||0)} redeem</small></div>${status}<button class="btn" onclick="showVoucherRedemptions('${v.id}')">👥</button>${exhausted?'':`<button class="btn" onclick="toggleVoucher('${v.id}',${!active})">${active?'Off':'On'}</button>`}</div>`}).join('')}
async function adminCreateVoucher(){if(!adminUnlocked)return openAdminGate();let code=prompt('Kode voucher:',randomVoucherCode());if(code===null)return;code=code.trim();if(!code)return msg('Kode voucher wajib diisi');let raw=prompt('Hadiah Diamond:', '100');if(raw===null)return;let reward=Number(raw);if(!Number.isInteger(reward)||reward<=0||reward>1000000000)return msg('Hadiah diamond harus 1 sampai 1.000.000.000');let maxRaw=prompt('Berlaku untuk berapa orang?', '3');if(maxRaw===null)return;let max=Number(maxRaw);if(!Number.isInteger(max)||max<=0||max>1000000)return msg('Batas redeem harus 1 sampai 1.000.000 orang');let r=await sb.rpc('lexiaa_admin_create_voucher',{p_key:adminKeySession,p_code:code,p_diamond_reward:reward,p_max_redemptions:max});if(r.error)return msg(adminErr(r));msg('Voucher berhasil dibuat: '+String(r.data?.code||code));await loadAdminVouchers()}
async function toggleVoucher(id,active){if(!adminUnlocked)return;let r=await sb.rpc('lexiaa_admin_set_voucher_active',{p_key:adminKeySession,p_voucher_id:id,p_active:!!active});if(r.error)return msg(adminErr(r));msg(active?'Voucher diaktifkan':'Voucher dinonaktifkan');await loadAdminVouchers()}
async function showVoucherRedemptions(id){if(!adminUnlocked)return;let list=await sb.rpc('lexiaa_admin_list_vouchers',{p_key:adminKeySession});if(list.error)return msg(adminErr(list));let voucher=(list.data||[]).find(v=>v.id===id);if(!voucher)return msg('Voucher tidak ditemukan');let r=await sb.rpc('lexiaa_admin_voucher_redemptions',{p_key:adminKeySession,p_voucher_id:id});if(r.error)return msg(adminErr(r));let rows=(r.data||[]).map(x=>`<div class="item"><div class="main"><b>${esc(x.display_name||'Lexiaa User')}</b><small>${esc(x.email||'')} · +${Number(x.diamond_reward||0).toLocaleString('id-ID')} 💎 · ${x.redeemed_at?new Date(x.redeemed_at).toLocaleString('id-ID'):'—'}</small></div></div>`).join('');openM('👥 Redeem · '+esc(voucher.code),rows||'<div class="empty">Belum ada yang redeem.</div>')}
async function loadAdminUsers(){if(!adminUnlocked)return openAdminGate();if(!user)return openAuth();let q=($('adminSearch')?.value||'').trim();$('adminUsers').innerHTML='<div class="empty">Memuat akun...</div>';let r=await sb.rpc('lexiaa_admin_list_users',{p_key:adminKeySession,p_search:q,p_limit:100});if(r.error){$('adminUsers').innerHTML='<div class="empty">Gagal memuat akun.<br><small>'+esc(adminErr(r))+'</small></div>';return}if(!r.data?.length){$('adminUsers').innerHTML='<div class="empty">Akun tidak ditemukan.</div>';return}$('adminUsers').innerHTML=r.data.map(x=>{let status=x.banned_at?'<span class="admin-status banned">BANNED</span>':'<span class="admin-status">ACTIVE</span>';return `<div class="item admin-user" onclick="openAdminUser('${x.id}')"><div class="thumb">${esc((x.display_name||'L')[0].toUpperCase())}</div><div class="main"><b>${esc(x.display_name||'Lexiaa User')}</b><small>${esc(x.email||'')} · 💎 ${Number(x.diamonds||0).toLocaleString('id-ID')} · ${Number(x.item_count||0)} item</small></div>${status}</div>`}).join('')}
async function openAdminUser(id){if(!adminUnlocked)return;adminSelectedUser=id;$('adminDetail').style.display='block';$('adminDetailBody').innerHTML='<div class="empty">Memuat detail...</div>';let r=await sb.rpc('lexiaa_admin_get_user',{p_key:adminKeySession,p_user_id:id});if(r.error){$('adminDetailBody').innerHTML='<div class="empty">Gagal memuat detail.<br><small>'+esc(adminErr(r))+'</small></div>';return}let x=r.data||{};let banned=!!x.banned_at;let effects=Array.isArray(x.name_effects)?x.name_effects:[];$('adminDetailBody').innerHTML=`<div><b style="font-size:20px">${esc(x.display_name||'Lexiaa User')}</b><div style="color:var(--m);font-size:12px;margin-top:3px">${esc(x.email||'')}</div></div><div class="admin-detail-grid"><div class="admin-stat"><small>Diamond</small><b>💎 ${Number(x.diamonds||0).toLocaleString('id-ID')}</b></div><div class="admin-stat"><small>Status</small><b>${banned?'🚫 Banned':'✓ Active'}</b></div><div class="admin-stat"><small>User ID</small><b style="font-size:11px;word-break:break-all">${esc(x.id)}</b></div><div class="admin-stat"><small>Daftar</small><b>${x.created_at?new Date(x.created_at).toLocaleString('id-ID'):'—'}</b></div></div>${banned?`<div class="empty" style="margin-top:10px">Alasan: ${esc(x.ban_reason||'Tidak ada alasan')}</div>`:''}<div class="admin-actions"><button class="btn primary" onclick="adminAddDiamonds('${x.id}')">＋ Tambah Diamond</button>${banned?`<button class="btn" onclick="adminUnban('${x.id}')">✓ Unban</button>`:`<button class="btn danger" onclick="adminBan('${x.id}')">🚫 Ban User</button>`}</div><div style="margin-top:16px"><div class="head"><h3>Owned Name Effects</h3><span class="tag">${effects.length} item</span></div><div class="admin-effects">${effects.length?effects.map(e=>`<div class="admin-effect"><b>${esc(e.name||'Effect')}</b><small>${esc(e.description||'')}${e.equipped?' · ✓ Sedang dipakai':''}</small></div>`).join(''):'<div class="empty">Belum punya Name Effect.</div>'}</div>`;$('adminDetail').scrollIntoView({behavior:'smooth',block:'start'})}
function closeAdminDetail(){adminSelectedUser=null;$('adminDetail').style.display='none'}
async function adminAddDiamonds(id){let raw=prompt('Berapa diamond yang ingin ditambahkan?','10');if(raw===null)return;let amount=Number(raw);if(!Number.isInteger(amount)||amount<=0)return msg('Jumlah diamond harus bilangan bulat positif');let reason=prompt('Alasan (opsional):','Admin Panel');let r=await sb.rpc('lexiaa_admin_add_diamonds',{p_key:adminKeySession,p_user_id:id,p_amount:amount,p_reason:reason||''});if(r.error)return msg(adminErr(r));msg('Diamond ditambahkan · saldo sekarang '+Number(r.data||0).toLocaleString('id-ID'));await loadAdminUsers();await openAdminUser(id)}
async function adminBan(id){let reason=prompt('Alasan ban (opsional):','');if(reason===null)return;let r=await sb.rpc('lexiaa_admin_ban_user',{p_key:adminKeySession,p_user_id:id,p_reason:reason});if(r.error)return msg(adminErr(r));msg('User berhasil di-ban');await loadAdminUsers();await openAdminUser(id);if(document.querySelector('#games.active')){loadLeaderboard();loadHomeChampion()}}
async function adminUnban(id){if(!confirm('Unban user ini?'))return;let r=await sb.rpc('lexiaa_admin_unban_user',{p_key:adminKeySession,p_user_id:id});if(r.error)return msg(adminErr(r));msg('User berhasil di-unban');await loadAdminUsers();await openAdminUser(id)}
async function logout(){await sb.auth.signOut();msg('Logout berhasil')}
window.addEventListener('load',()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');init();setTimeout(()=>loadHomeChampion(),1200)});
